[package]
name = "buildrs-problem"
version = "0.1.0"
authors = ["Hans-Christian Esperer <hc@caiberp.ai>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
